#pragma once
// ============================================================================
// ModalImpactComponent.h
// ============================================================================
//
// PURPOSE
// -------
// Detects physics collisions on the owner actor, computes kinetic energy
// and per-mode excitation amplitudes, and broadcasts a delegate for the
// ModalMetaSoundBridge to drive MetaSound synthesis.
//
// SCIENTIFIC BASIS
// ----------------
// VELOCITY-BASED KE (new in this version):
//   KE = ½mv²  using the physics velocity cached each tick BEFORE the
//   collision resolves. This is more numerically stable than using the
//   NormalImpulse vector from OnComponentHit, which can vary ±30% for
//   identical drops due to physics solver sub-step timing.
//
// HERTZ CONTACT FORCE SHAPING (Chadwick, Zheng & James 2012):
//   The contact force pulse between two elastic bodies has a characteristic
//   duration T_c ∝ (m_eff / k_Hertz)^0.4 (Johnson 1985, Contact Mechanics).
//   The Fourier transform of a half-sine pulse of duration T_c:
//     F(ω) = sinc(ω·T_c / 2π)
//   acts as a low-pass filter on modal excitation — hard/fast impacts
//   (short T_c) excite all frequencies; soft/slow impacts (long T_c)
//   excite only low modes. This produces the perceptual difference between
//   a gentle tap and a hard slam even at the same total energy.
//   "The addition of acceleration noise significantly complements the
//   standard modal sound algorithm, especially for small objects."
//   — Chadwick et al. (2012), Abstract.
//
// AMPLITUDE FORMULA (per mode k):
//   A_k = φ_k(v) × √(KE/KE_max) × η_k × F_k(v_impact) × jitter
//   where:
//     φ_k(v)       = participation factor from DataAsset (van den Doel 1998)
//     √(KE/KE_max) = energy scale (Klatzky et al. 2000: loudness ∝ √force)
//     η_k          = radiation efficiency (stored in GlobalAmplitude)
//     F_k(v)       = Hertz sinc weight at mode frequency and impact speed
//     jitter       = ±15% random variation (Rath & Rocchesso 2005)
//
// ============================================================================

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "OfflinePipeline/ModalSoundDataAsset.h"
#include "ModalImpactComponent.generated.h"

/**
 * Delegate broadcast on every qualifying impact event.
 *
 * ImpactPoint       — world-space contact location
 * KineticEnergy     — ½mv² in joules (from pre-impact velocity)
 * RelativeSpeed     — pre-impact speed in m/s (for Hertz contact weight)
 * ClosestVertex     — index into DataAsset surface vertex array
 * DataAsset         — ModalSoundDataAsset for this object
 * ImpactNormal      — world-space surface normal at contact
 */
DECLARE_DYNAMIC_MULTICAST_DELEGATE_SixParams(
    FOnModalImpact,
    FVector,               ImpactPoint,
    float,                 KineticEnergy,
    float,                 RelativeSpeed,
    int32,                 ClosestVertex,
    UModalSoundDataAsset*, DataAsset,
    FVector,               ImpactNormal
);

UCLASS(ClassGroup=(Audio), meta=(BlueprintSpawnableComponent),
       DisplayName="Modal Impact Component")
class PHYSICAL_AUDIO_API UModalImpactComponent : public UActorComponent
{
    GENERATED_BODY()

public:
    UModalImpactComponent();

    // ── CONFIGURATION ──────────────────────────────────────────────────────

    /** The DataAsset generated by the offline FEM pipeline. */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Modal Sound")
    UModalSoundDataAsset* ModalDataAsset;

    /**
     * Minimum kinetic energy (J) to trigger a sound event.
     * Filters out resting contact, micro-vibrations, and sliding friction.
     *
     * TUNING GUIDE:
     *   Start at 1% of a typical drop impact's KE.
     *   KE = 0.5 × mass_kg × (drop_velocity_m_s)²
     *   Example: 5 kg object dropped 1 m → v = √(2·9.8·1) ≈ 4.4 m/s
     *            KE = 0.5 × 5 × 19.6 = 49 J → set MinImpactEnergy ≈ 5 J
     */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Modal Sound",
              meta=(ClampMin="0.0"))
    float MinImpactEnergy = 5.0f;

    /**
     * Maximum kinetic energy (J) for amplitude normalisation.
     * Impacts at or above this KE play at full amplitude.
     * Set to the KE of the hardest expected impact.
     */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Modal Sound",
              meta=(ClampMin="1.0"))
    float MaxImpactEnergy = 200000.0f;

    /**
     * Minimum seconds between consecutive impact events.
     * Prevents retriggering during tumble/roll sequences.
     * 0.1–0.2 s is typical.
     */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Modal Sound",
              meta=(ClampMin="0.0"))
    float ImpactCooldown = 0.15f;

    /**
     * Global volume multiplier applied to all mode amplitudes.
     * Use to adjust loudness without changing the DataAsset.
     */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Modal Sound",
              meta=(ClampMin="0.0", ClampMax="4.0"))
    float VolumeScale = 1.0f;

    /**
     * Material Hertz contact hardness override.
     * Matches the 'contact_hardness' value for the assigned material.
     * Controls estimated contact duration:
     *   T_c ∝ 1/sqrt(hardness) — harder = shorter = more high-freq content.
     * Exposed here so it can be set per-Blueprint without regenerating the
     * DataAsset. Default 0.8 matches HeavyMetal preset.
     * Reference: Chadwick et al. (2012) §3; Johnson (1985) Contact Mechanics.
     */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Modal Sound",
              meta=(ClampMin="0.01", ClampMax="2.0"))
    float ContactHardness = 0.8f;

    // ── OUTPUT ─────────────────────────────────────────────────────────────

    UPROPERTY(BlueprintAssignable, Category="Modal Sound")
    FOnModalImpact OnModalImpact;

    // ── PUBLIC API ─────────────────────────────────────────────────────────

    /**
     * Finds the surface vertex in the DataAsset closest to WorldPosition.
     * Uses the render mesh vertex cache built at BeginPlay.
     * Impact sounds vary spatially because different vertices have
     * different participation factors for each mode.
     */
    UFUNCTION(BlueprintCallable, Category="Modal Sound")
    int32 FindClosestVertex(FVector WorldPosition) const;

    /**
     * Computes per-mode excitation amplitudes for one impact event.
     *
     * Full formula (van den Doel & Pai 1998 + Chadwick et al. 2012):
     *   A_k = φ_k(vertex) × √(KE/KE_max) × η_k × F_k(speed) × jitter
     *
     * where F_k(speed) = sinc(ω_k · T_c(speed) / 2π)
     * and   T_c(speed) = T_c_base × (v_ref / speed)^0.2
     *                  = contact duration (Hertz theory, Johnson 1985)
     *
     * Args:
     *   VertexIndex   — closest surface vertex (from FindClosestVertex)
     *   KineticEnergy — ½mv² in joules
     *   RelativeSpeed — pre-impact speed in m/s
     *   ImpactNormal  — surface normal at impact point (reserved for future
     *                   use in direction-dependent excitation)
     */
    UFUNCTION(BlueprintCallable, Category="Modal Sound")
    TArray<float> ComputeModeAmplitudes(int32   VertexIndex,
                                         float   KineticEnergy,
                                         float   RelativeSpeed,
                                         FVector ImpactNormal) const;

protected:
    virtual void BeginPlay() override;
    virtual void TickComponent(float DeltaTime, ELevelTick TickType,
                                FActorComponentTickFunction* Fn) override;

private:
    UFUNCTION()
    void OnHit(UPrimitiveComponent* HitComp, AActor* OtherActor,
               UPrimitiveComponent* OtherComp, FVector NormalImpulse,
               const FHitResult& Hit);

    void BuildVertexCache();

    UPROPERTY() UPrimitiveComponent* OwnerMesh = nullptr;

    /** Render-mesh vertex positions in local space (centimetres). */
    TArray<FVector> CachedVerts;

    /**
     * Physics velocity cached each tick BEFORE collision.
     * Already converted to m/s in TickComponent.
     * Used to compute KE = ½mv² without relying on the noisy impulse vector.
     */
    FVector PreImpactVel = FVector::ZeroVector;

    float LastImpactTime = -999.f;
};