#pragma once
// ============================================================================
// ModalImpactComponent.h
// ============================================================================
//
// PURPOSE
// -------
// Detects physics collisions on the owner actor, decomposes velocity into
// normal (impact) and tangential (sliding) components, computes per-mode
// amplitudes for each, and broadcasts separate delegates for the bridge.
//
// WHAT CHANGED FROM PREVIOUS VERSION
// ------------------------------------
// 1. VERTEX INDEX FIX (critical):
//    FindClosestVertex now searches FEMSurfaceVertexPositions stored in the
//    DataAsset rather than the render mesh LOD0 vertices. The render mesh and
//    the FEM mesh have different vertex counts due to subdivision — searching
//    the wrong mesh returned indices that indexed into the wrong part of
//    VertexParticipation, silently breaking all spatial impact variation.
//
// 2. CONTACT HARDNESS FROM DATAASSET:
//    ContactHardness is now read from DataAsset->ContactHardness at BeginPlay
//    rather than using a fixed default. A Wood DataAsset now automatically uses
//    wood-appropriate Hertz contact shaping without manual override.
//    The override property is kept for Blueprint tuning.
//
// 3. SLIDING SOUND DELEGATE (new):
//    FOnModalSlide is broadcast continuously from TickComponent when the body
//    is in contact and sliding. This uses TangentialSpeed and NormalForce to
//    drive a separate scrape MetaSound. The bridge maintains a persistent
//    audio component for the scrape sound (no per-frame spawning).
//
// AMPLITUDE FORMULA (impact, per mode k):
//   A_k = φ_k(v) × √(KE/KE_max) × η_k × sinc(f_k·T_c) × jitter
//   where T_c = C_mat / v^0.2   (Hertz contact theory, Johnson 1985)
//
// SCRAPE AMPLITUDE FORMULA (per mode k):
//   A_k = DragSensitivity_k × TangentialSpeed × NormalForce_normalised × jitter
//   Reference: Rath & Rocchesso (2005) §3.
// ============================================================================

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "OfflinePipeline/ModalSoundDataAsset.h"
#include "ModalImpactComponent.generated.h"

// ── Impact delegate ───────────────────────────────────────────────────────
// Broadcast once per qualifying impact event.
DECLARE_DYNAMIC_MULTICAST_DELEGATE_SixParams(
    FOnModalImpact,
    FVector,               ImpactPoint,
    float,                 KineticEnergy,
    float,                 RelativeSpeed,      // normal component only
    int32,                 ClosestVertex,       // index into FEM surface mesh
    UModalSoundDataAsset*, DataAsset,
    FVector,               ImpactNormal
);

// ── Slide delegate ────────────────────────────────────────────────────────
// Broadcast each tick while the body is actively sliding.
// TangentialSpeed — m/s component perpendicular to contact normal
// NormalForce     — normalised [0,1] clamped from normal KE proxy
//                   (used to shape scrape amplitude: louder when pressed harder)
// ContactPoint    — world-space average contact position
// DataAsset       — same DataAsset as the impact delegate
DECLARE_DYNAMIC_MULTICAST_DELEGATE_FiveParams(
    FOnModalSlide,
    float,                 TangentialSpeed,
    float,                 NormalForce,
    FVector,               ContactPoint,
    UModalSoundDataAsset*, DataAsset,
    int32,                 ClosestVertex
);


DECLARE_DYNAMIC_MULTICAST_DELEGATE_FourParams(
	FOnSampleBasedImpact,
	FVector,               ImpactPoint,
	float,                 KineticEnergy,
	float,                 RelativeSpeed,      // normal component only
	FVector,               ImpactNormal
);

DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(
	FOnSampleBasedSlide,
	float,                 TangentialSpeed,
	float,                 NormalForce,
	FVector,               ContactPoint
);

UCLASS(ClassGroup=(Audio), meta=(BlueprintSpawnableComponent),
       DisplayName="Modal Impact Component")
class PHYSICAL_AUDIO_API UModalImpactComponent : public UActorComponent
{
    GENERATED_BODY()

public:
    UModalImpactComponent();

    // ── CONFIGURATION ──────────────────────────────────────────────────────

    /** The DataAsset generated by the offline FEM pipeline. */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Modal Sound")
    UModalSoundDataAsset* ModalDataAsset;

    /**
     * Minimum kinetic energy (J) to trigger an impact sound.
     * Filters out resting contact and micro-vibrations.
     *
     * Formula: KE = 0.5 × mass(kg) × NormalSpeed(m/s)²
     * Examples for a 5 kg plank:
     *   0.3 m/s drop → KE = 0.225 J  (tip barely touching floor — silent)
     *   1.0 m/s drop → KE = 2.5 J    (gentle fall)
     *   3.0 m/s drop → KE = 22.5 J   (moderate fall)
     *
     * Default 1.0 J. Previous default was 5.0 J, which was silencing gentle
     * drops of heavy planks (low speed + high mass still gives a real impact).
     * For small light objects (< 1 kg) raise to 2.0–5.0 to filter resting noise.
     * For heavy planks (> 10 kg) can lower to 0.5.
     */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Modal Sound",
              meta=(ClampMin="0.0"))
    float MinImpactEnergy = 1.0f;

    /**
     * KE (J) that maps to full amplitude. Impacts above this are clamped.
     */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Modal Sound",
              meta=(ClampMin="1.0"))
    float MaxImpactEnergy = 200000.0f;

    /**
     * Minimum seconds between consecutive impact events.
     * Prevents rapid re-triggering during tumble/roll.
     *
     * Default 0.20s. For long planks that bounce, both ends can hit
     * within < 0.15s — use 0.20–0.25s to ensure only the primary impact
     * sounds (the second bounce at lower speed would produce a thud).
     * For small objects that tumble rapidly (coins, dice) lower to 0.08–0.10s.
     */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Modal Sound",
              meta=(ClampMin="0.0"))
    float ImpactCooldown = 0.20f;

    /**
     * Global volume multiplier applied to all mode amplitudes.
     */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Modal Sound",
              meta=(ClampMin="0.0", ClampMax="4.0"))
    float VolumeScale = 1.0f;

    /**
     * Hertz contact hardness override.
     * Normally read automatically from DataAsset->ContactHardness at BeginPlay.
     * Exposed here so you can fine-tune per-Blueprint without regenerating assets.
     * Default 0.8 (HeavyMetal) — will be overwritten by DataAsset value at BeginPlay.
     */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Modal Sound",
              meta=(ClampMin="0.01", ClampMax="2.0"))
    float ContactHardness = 0.8f;

    /**
     * Scales the Hertz contact duration T_c used in the sinc excitation filter.
     *
     *   T_c = (0.0025 / sqrt(ContactHardness)) × ContactDurationScale / v^0.2
     *
     * Primarily affects AMPLITUDE: smaller values let more modes through the
     * sinc filter → louder impact. Does NOT significantly change tonal character
     * because at values ≤ 0.5, sinc ≈ 1.0 for all modes and they all scale
     * proportionally — the spectral shape (mode ratios) is unchanged.
     *
     * Keep at 1.0 for physically correct behaviour. Only lower if impacts
     * are consistently too quiet after tuning MasterGain and ContactHardness.
     * Range 0.3–1.0 for fine-tuning. Does NOT fix the "soft/dull" character
     * problem — use ContactGain (via ContactHardness) for that.
     *
     * Default 1.0.
     */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Modal Sound",
              meta=(ClampMin="0.001", ClampMax="2.0"))
    float ContactDurationScale = 1.0f;

    /**
     * normal to count as an impact (not sliding).
     * 0.30 = at least 30% normal component.
     * Raise if sliding still triggers impacts. Lower if glancing hits are missed.
     */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Modal Sound",
              meta=(ClampMin="0.0", ClampMax="1.0"))
    float MinNormalFraction = 0.30f;

    /**
     * Minimum tangential speed (m/s) to start broadcasting slide events.
     * Filters resting or barely-moving contact.
     */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Modal Sound",
              meta=(ClampMin="0.0"))
    float MinSlideSpeed = 0.05f;

    /**
     * How quickly the slide sound fades in/out as TangentialSpeed changes.
     * One-pole smoothing filter applied each tick:
     *   SmoothedSpeed = lerp(SmoothedSpeed, TangentialSpeed, SlideSmoothing)
     * Range 0.0–1.0. Lower = smoother, slower response.
     *
     * Default 0.50 (~67ms to 90% at 60fps).
     *
     * Why 0.50 and not lower:
     *   At 0.15 (250ms rise time), fast changes in tangential speed during
     *   impact/bounce cycles produce a lagging, anaemic scrape that doesn't
     *   react to the physics. Objects that slide briefly between bounces sound
     *   like they barely touch the surface. 0.50 gives crisp, responsive
     *   scrape onset that matches visible motion.
     *
     * The bridge's ScrapeGainSmoothing (default 0.20) adds a second layer of
     * smoothing on top, so there is no risk of pops at this setting.
     *
     * Reduce to 0.20–0.30 only for very heavy, slow-moving objects (stone
     * blocks, heavy machinery) where speed changes are naturally gradual.
     */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Modal Sound",
              meta=(ClampMin="0.01", ClampMax="1.0"))
    float SlideSmoothing = 0.50f;

    // ── OUTPUT DELEGATES ───────────────────────────────────────────────────

    UPROPERTY(BlueprintAssignable, Category="Modal Sound")
    FOnModalImpact OnModalImpact;

    UPROPERTY(BlueprintAssignable, Category="Modal Sound")
    FOnModalSlide OnModalSlide;
	
	UPROPERTY(BlueprintAssignable, Category="SampleBased Sound")
	FOnSampleBasedImpact OnSampleBasedImpact;

	UPROPERTY(BlueprintAssignable, Category="SampleBased Sound")
	FOnSampleBasedSlide OnSampleBasedSlide;

    // ── PUBLIC API ─────────────────────────────────────────────────────────

    /**
     * Finds the FEM surface vertex closest to WorldPosition.
     *
     * CHANGE FROM PREVIOUS VERSION:
     *   Now searches DataAsset->FEMSurfaceVertexPositions instead of the
     *   render mesh LOD0. The two meshes differ due to subdivision (e.g. a cube
     *   has 8 render verts but 386 FEM verts). Using the render mesh index to
     *   look up VertexParticipation was reading from the wrong entries.
     *
     * Returns an index valid for Mode.VertexParticipation[index].
     */
    UFUNCTION(BlueprintCallable, Category="Modal Sound")
    int32 FindClosestVertex(FVector WorldPosition) const;

    /**
     * Computes per-mode excitation amplitudes for one impact event.
     *
     *   A_k = φ_k(v) × √(KE/KE_max) × η_k × sinc(f_k·T_c) × jitter
     *
     * T_c = C_mat / v^0.2  (Hertz theory, Johnson 1985)
     * C_mat = 0.0025 / √(ContactHardness)   (from DataAsset, not hardcoded)
     */
    UFUNCTION(BlueprintCallable, Category="Modal Sound")
    TArray<float> ComputeModeAmplitudes(int32   VertexIndex,
                                         float   KineticEnergy,
                                         float   RelativeSpeed,
                                         FVector ImpactNormal) const;

    /**
     * Computes per-mode scrape amplitudes for one tick of sliding contact.
     *
     *   A_k = DragSensitivity_k × SmoothedTangentialSpeed × NormalForce × jitter
     *
     * DragSensitivity_k is pre-computed in the pipeline as:
     *   η_k / (1 + (f_k / f_0)²)
     * so low modes dominate (low-frequency emphasis in scraping).
     * Reference: Rath & Rocchesso (2005) §3.
     */
    UFUNCTION(BlueprintCallable, Category="Modal Sound")
    TArray<float> ComputeScrapeAmplitudes(int32 VertexIndex,
                                           float TangentialSpeed,
                                           float NormalForce) const;

protected:
    virtual void BeginPlay() override;
    virtual void TickComponent(float DeltaTime, ELevelTick TickType,
                                FActorComponentTickFunction* Fn) override;

private:
    UFUNCTION()
    void OnHit(UPrimitiveComponent* HitComp, AActor* OtherActor,
               UPrimitiveComponent* OtherComp, FVector NormalImpulse,
               const FHitResult& Hit);

    // FEM vertex cache is no longer built from the render mesh.
    // FindClosestVertex reads DataAsset->FEMSurfaceVertexPositions directly.
    // BuildVertexCache() is removed — no cache needed since the DataAsset
    // already stores positions in a contiguous array.

    UPROPERTY() UPrimitiveComponent* OwnerMesh = nullptr;

    // Physics velocity (m/s) cached one tick before collision.
    FVector PreImpactVelocity = FVector::ZeroVector;

    // Sliding state — tracked across ticks for the slide delegate.
    bool  bIsSliding          = false;
    float SmoothedSlideSpeed  = 0.f;
    FVector LastContactPoint  = FVector::ZeroVector;
    FVector LastContactNormal = FVector::UpVector;
    float LastSlideTime       = -999.f;     // time of last OnHit during a slide
    int32 LastSlideVertex     = 0;

    float LastImpactTime = -999.f;
};